[project]
name = "pytorch_sandbox"
description = "A place to play with pytorch."
version = "0.0.1"

[project.scripts]
mnist-demo = "pytorch_sandbox.mnist_demo:main"
mnist-train = "pytorch_sandbox.mnist_train:main"

[project.urls]
"GitHub" = "https://github.com/jbcoe/pytorch-sandbox"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
check_untyped_defs = true

[tool.pyright]
pythonVersion = "3.12"

[tool.coverage.run]
concurrency = ["thread", "multiprocessing"]
source = ["."]

[tool.interrogate]
verbose = "2"
ignore-init-method = false
omit-covered-files = false
ignore-init-module = true
